export const FETCH_COMPANY_SEARCH_START =
  "FETCH_COMPANY_SEARCH_START"
export const FETCH_COMPANY_SEARCH_SUCCESS =
  "FETCH_COMPANY_SEARCH_SUCCESS"
export const FETCH_COMPANY_SEARCH_FAILED =
  "FETCH_COMPANY_SEARCH_FAILED"

