export const FETCH_UPLOADING_PENDING_DOC_LIST_START =
  "FETCH_UPLOADING_PENDING_DOC_LIST_START"
export const FETCH_UPLOADING_PENDING_DOC_LIST_SUCCESS =
  "FETCH_UPLOADING_PENDING_DOC_LIST_SUCCESS"
export const FETCH_UPLOADING_PENDING_DOC_LIST_FAILED =
  "FETCH_UPLOADING_PENDING_DOC_LIST_FAILED"
